name: ServerMenu
main: com.gogless.menu.MenuPlugin
version: 1.0.0
api-version: '1.21'
author: Gogless
description: A simple server menu plugin.
commands:
  menu:
    description: Opens the server menu.
    usage: /menu
